CREATE table users (
    id number GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar2(50) NOT NULL UNIQUE,
    password varchar2(255) NOT NULL,
    email varchar2(100) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);